---
label: Services
hide_body: false
fields:
- name: thumb
  type: file
  config:
    maxSize: 64
  label: Thumb
- name: title
  type: text
  config:
    required: false
  label: Title
  description: Add title here
pages:
- articles/the-dark-side-of-cloud.md
